ory/meta

- CONTRIBUTING.md
Matched security vulnerability disclosure emails so they both point to security@ory.sh.
> docs: matched sec-email

- scripts/sync.sh
Currently there is always a newline added to the adopters and ecosystem sections whenever sync runs.
Closes https://github.com/ory/kratos/pull/724
Closes https://github.com/ory/hydra/pull/2083
> fix: match newline after adopters and ecosystem

- package-lock.json
- package.json
The CI script installing prettier uses jq to get the prettier version and expects it to be under `devDependencies`
> fix: move prettier to devDependencies

- templates/repository/library/.github/pull_request_template.md
https://github.com/ory/meta/issues/32
Is it unnecessary here, since the CLA-Bot notifies you anyway if you have not signed it? 
But at least its mentioned I guess...
> docs: add CLA to PR template

- CONTRIBUTING.md
There is still an error in
Line 163 the link to /docs/README.md
is broken (which I put in there btw.)
I tried to use (../../README.md) to make it work, but it does not and I dont know why.
> docs: contributing link fix

- scripts/update-repository-templates.sh
- templates/repository/common/.github/ISSUE_TEMPLATE/config.yml
- templates/repository/common/CONTRIBUTING.md
- templates/repository/library/.github/pull_request_template.md
- templates/repository/server/.github/pull_request_template.md
changed the scripts to provide the correct link to github discussions for each ory project.
should the replacement be added to synch.sh as well? (afaik sync.sh doesnt change the templates but to be consistent maybe). Let me know and I add it.
> docs: change to gh discussions

- scripts/update-repository-templates.sh
- templates/repository/common/.github/ISSUE_TEMPLATE/config.yml
This aims to fix the broken link generated by the script:
https://github.com/ory/hydra/pull/2241/files#diff-1c0d972ee49103af56fd608a77a28e1eb12f6908f263f0f183d46868fdcd8ea2R4
Please note that the org is missing, the repository is uppercase (it should be lowercase), and github.com does not use `www`.
> feat: add repo replace

- scripts/sync.sh
I removed $workdir in [the last commit](https://github.com/ory/meta/commit/d3a2438027877f14e8433bb44431544b9b91d210#diff-1272bfef55f69c7d75b2a92057586cba93ba4ced6160199525e011eab54be9c2) by accident. 
Just noticed it and put it in again.
> fix: fix $workdir

- templates/repository/common/PROJECTS.md
Hydra is not directly able to connect to LDAP and other User-DB-solutions. So that section is misleading as the integration need to be implemented on the UI-interface side.
CC @jaredpreston  Maybe you have a proposal how to characterize hydra a bit better than this?
> Remove LDAP reference

- package-lock.json
- templates/repository/common/CONTRIBUTING.md
$REPOSITORY will be replaced with "ory/repositoryName" and then cla-assistant links in CONTRIBUTING.md will work from there as well.
> fix: cla-assistant link

- templates/repository/common/ADOPTERS.md
Removed a stray anchor tag, CI was failing with 
`I found a </a> tag here but there isn't an opening <a ...> tag above.`
I added a proper link to https://opencollective.com/ory. 
Or would it be better to remove the link?
The CI run: https://app.circleci.com/pipelines/github/ory/kratos/2850/workflows/54eb19b0-6578-4eff-ad67-cd48246fd271/jobs/18476
> fix: stray anchor tag

- scripts/sync.sh
Failing CI example: https://app.circleci.com/pipelines/github/ory/keto/1024/workflows/22b24e30-9cda-410a-ac68-b5cceed66294/jobs/7124
This fix ensures that all rendered files (like CONTRIBUTING.md or README.md) are formatted.
> fix: format rendered files

- templates/repository/common/CONTRIBUTING.md
Closes https://github.com/ory/meta/issues/99
This adds a list of possible subsystem prefixes
e.g.
https://github.com/ory/hydra/labels?q=package
https://github.com/ory/kratos/labels?q=package
for the other repos it shows no labels, but it should be self explanatory?
https://github.com/ory/fosite/labels?q=package
> docs: add list of subsystem prefixes

- .github/workflows/sync.yml
- README.md
- templates/repository/common/.github/ISSUE_TEMPLATE/config.yml
- templates/repository/common/ADOPTERS.md
- templates/repository/common/PROJECTS.md
- templates/repository/library/.github/pull_request_template.md
- templates/repository/server/.github/pull_request_template.md
Finally changing all the templates in /meta to from ORY to Ory. 
This will probably crop up over time, but I try to take care of it whenever possible. 
Next up would be ory/docs and then the individual repos.
> chore: ORY -> Ory

- scripts/sync.sh
- templates/repository/common/.github/CODEOWNER
Will add individual CODEOWNER files in each repo. The default of what was previously there should stay as our sync script does not delete files.
> fix: remove global CODEOWNER file

- install.sh
There is no flag as `-v` according to the codes. The version must be set as a tag. This commit fixes the usage note
> fix: remove the invalid flag from the usage note

- .github/workflows/sync.yml
This would add CONTRIBUTING to the docs and a proper readme. 
Do we need to add the 
```
```
to the README? 
- Happy to open another issue to make the README look more in line to ory/kratos etc. 
Also we can probably delete this part from the [sync.sh](https://github.com/ory/meta/blob/master/scripts/sync.sh)? 
```
if [ -d "$workdir/docs/docs" ]; then
cat <<EOF > "$workdir/docs/docs/contributing.md"
```
I would use CONTRIBUTING and combine it with 
https://github.com/ory/docs/blob/master/docs/ecosystem/contributing.md
to make a "general" contributing guide, that is in parts automated, in parts has some general sections added.
> fix: add docs to sync workflow

- templates/repository/common/.github/ISSUE_TEMPLATE/config.yml
This changes the forum URL to  $DISCUSSIONS which will always use the Ory Org discussions if there is none on the repo (i.e. for all repos except kratos,hydra,oathkeeper,keto).
Closes https://github.com/ory/dockertest/issues/361
> fix: use correct discussions repo

- .github/workflows/format.yml
This uses the Prettier config version defined in `package.json`, which is also available via `npm run format`. Meaning that CI will enforce exactly the same style that running Prettier locally creates.
> Update the Prettier CI job

- templates/repository/common/.github/workflows/conventional_commits.yml
Here comes v2 of the new system to enforce conventional commit style on pull requests. Big thanks to @zepatrik for providing detailed feedback about what didn't work with v1, providing pointers to a better solution, and even going the extra mile and submitting a possible upstream fix! 🚀 
V2 finally provides the right abstractions that Ory needs (I think):
- a centralized Ory-specific set of default titles and scopes
- most repos can use those and don't need any custom config files at all
- a generic workflow definition that can be pushed to all repos as often as we want without overriding customizations
- ability for individual repos to override particular settings via a separate file
- ability to _add_ titles and scopes to the existing sets
One problem with all previous versions was that …
> feat: conventional commits v2

- scripts/sync.sh
CI doesn't have all the paths set that my dev machine has so this bug slipped through.
> fix: call Prettier in CI-compatible way

- templates/repository/common/CONTRIBUTING.md
Now that CircleCI is no longer used, contributors are no longer required to create a CircleCI account.
> docs: remove mention of CircleCI

- scripts/sync.sh
The new shebang is more flexible because it also works in places that use a custom installation of Bash.
> Improve shebang

- templates/repository/common/.github/ISSUE_TEMPLATE/DESIGN-DOC.yml
- templates/repository/common/.github/workflows/stale.yml
- templates/repository/common/CONTRIBUTING.md
- templates/repository/common/PROJECTS.md
- templates/repository/common/SECURITY.md
- templates/repository/library/.github/pull_request_template.md
- templates/repository/server/.github/pull_request_template.md
via grammarly (https://marketplace.visualstudio.com/items?itemName=znck.grammarly)
> fix: typos and grammar

- scripts/sync.sh
Sync headers shouldn't occur in pull-request templates because they are displayed verbatim to the user.
> chore: finetune sync headers

- CONTRIBUTING.md
- SECURITY.md
- templates/repository/common/CONTRIBUTING.md
- templates/repository/common/SECURITY.md
These headers were hard-coded and showed up even in the original file. Since https://github.com/ory/meta/pull/171 shipped, they are no longer necessary.
> chore: remove old headers

- templates/repository/common/.github/workflows/format.yml
All repos have the same formatting now, so we can move this into the meta repo.
> chore: unified formatting for all repos

- scripts/sync.sh
The sync script keeps committing package-lock.json to all repos, breaking stuff.
> fix: do not commit package-lock.json

- Makefile
- scripts/sync.sh
https://github.com/ory/cli/pull/257 changed the name of the command to add copyright headers to files. Ship this PR after Ory CLI v0.1.48 ships.
> chore: update Ory CLI with breaking changes to the format task
