ory/meta

tmp/faq.md

Added kratos section and a question.

Added kratos section

---

scripts/release.sh

feat: use minor, patch, major as args

---

tools/ory-dev/cmd/fizz_migrations_tests_sync.go

fix: ory-dev syntax error

---

templates/repository/common/.github/workflows/closed_references.yml

feat: add closed reference notifier to repo templates

---

tmp/faq.md

FAQs about bug bounties/enterprise version

docs(faq): added two items

---

tmp/faq.md

Is it possible to set a custom claim in JWT access tokens?
Apparently not answered in the docs
(from the discord)

docs(faq): added hydra faq

---

scripts/sync-library.sh
scripts/sync-server.sh
scripts/sync.sh

fix: create PR instead of push to master

---

.github/workflows/format.yml
.gitignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
SECURITY.md
package-lock.json
package.json
templates/repository/common/CODE_OF_CONDUCT.md
templates/repository/common/CONTRIBUTING.md
templates/repository/common/SECURITY.md
tmp/faq.md

Most of the downstream repos use it and there should be no error when this repo gets updated.
Closes https://github.com/ory/milestone-action/issues/3

feat: add formatting using prettier

---

scripts/sync.sh
templates/repository/common/.github/workflows/closed_references.yml
templates/repository/common/.reference-ignore

This will allow individual ignore entries for every repo.

feat: use .reference-ignore instead of input for closed-reference action

---

templates/repository/common/.github/workflows/closed_references.yml
templates/repository/common/.github/workflows/labels.yml
templates/repository/common/.github/workflows/stale.yml
templates/repository/server/.github/workflows/milestone.yml

Closes https://github.com/ory/fosite/issues/494

feat: disable scheduled jobs on forks

---

.github/workflows/sync.yml

Added ORYworks repository to sync. 
If this is correct now, it should also close https://github.com/ory/oryworks/pull/2

feat: added ORYworks to sync

---

CONTRIBUTING.md

https://github.com/ory/meta/issues/32
Added short mention of the CLA.
Do you think it should be expanded (subsection explaining the CLA contents in a few bulletpoints for example?)

docs: add CLA mention

---

community_hangouts.md

Added a short summary of the last two hangouts.
If well received I plan to release something like this for every hangout.

docs: added hangout summary

---

releases/kratos/0.5.0-alpha.1.md

docs: tiny typo

---

community_hangouts.md

Added summary of the community hangout on 14.10.20

docs: hangout summary

---

releases/kratos/0.5.0-alpha.1.md

I fixed up some grammer and added a few callouts.

fix:Update 0.5.0-alpha.1.md

---

releases/kratos/0.5.0-alpha.1.md

Very nice release notes! I think this reads slightly better.

docs: Print only names of contributors

---

CONTRIBUTING.md
releases/kratos/0.5.0-alpha.1.md
templates/repository/common/CONTRIBUTING.md

Added a few sections and stuff for newcomers. 
This is still WIP, so dont merge yet please. 
But do leave feedback, if I am going in the right direction with this.

docs: CONTRIBUTING.md overhaul

---

static/adopters/datadetect.svg
templates/repository/common/ADOPTERS.md

docs: add datadetect adopters

---

.github/workflows/sync.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
community_hangouts.md
package-lock.json
package.json
releases/kratos/0.5.0-alpha.1.md
templates/repository/common/CODE_OF_CONDUCT.md
templates/repository/common/CONTRIBUTING.md
templates/repository/library/.github/pull_request_template.md
tmp/faq.md

The push trigger should only run when there are changes in `templates/**`. The pattern was wrongly defined so that it never matched.

ci: fix sync action

---

CONTRIBUTING.md

Reverts ory/meta#63
https://github.com/ory/meta/pull/63#issuecomment-731200492
@vinckr

Revert "docs: contributing link fix"

---

templates/repository/common/CONTRIBUTING.md

https://github.com/ory/meta/pull/63

docs: really fix link

---

scripts/sync.sh

based on your comment https://github.com/ory/meta/issues/33#issuecomment-723915534, just switching the commands should fix it? i dont know how to test locally

fix: missing template variable

---

templates/repository/library/.github/pull_request_template.md
templates/repository/server/.github/pull_request_template.md

Changed the section about forum to github discussions.
There also need to be some changes in CONTRIBUTING.md but I would do those when we activate discussions for the whole org.

docs: change pr template

---

.github/workflows/sync.yml
README.md
scripts/sync-action.sh
scripts/sync-library.sh
scripts/sync-server.sh
scripts/sync.sh

Reverted my changes from https://github.com/ory/meta/pull/74 (except the change to include ory/works in the script again)
Documented everything I could think of in sync.sh.
Also added documentation on the sync Action and sync.yml to README.

docs: document sync.sh 

---

community_hangouts.md
package-lock.json
package.json
templates/repository/common/ADOPTERS.md

Note that there are some problems that are caused due to templating. Because of that, I did not add it to the CI yet. See https://github.com/kevgo/text-runner/issues/1401 for more info.

feat: add text-run and fix problems found by it

---

.github/workflows/text-run.yml
package-lock.json
package.json

This should speed up CI execution time significantly as text-runner is not custom build anymore.

ci: use text-runner 5.0.0

---

.github/workflows/sync.yml
templates/repository/common/CONTRIBUTING.md

Adressing mitars suggestions in https://github.com/ory/meta/pull/100:
https://github.com/ory/meta/pull/100#discussion_r640813071
This should make it clearer that the prefix is just a rough description, also added some explanation why the prefix is important.

contributing update

---

templates/repository/common/CONTRIBUTING.md

addresses https://github.com/ory/hydra/pull/2553.
this showed me i should test smaller changes as well...

fix: link to commit prefixes

---

scripts/sync.sh

as discussed in https://github.com/ory/kratos/issues/1423.
I tested the line I added locally and it worked fine !

fix: sync CoC

---

saved_replies/mark-as-draft.md

Found it by accident and thought its a neat reply 🙂

docs: canned reply mark as draft

---

templates/repository/common/CONTRIBUTING.md

As per https://github.com/ory/kratos/pull/1449#discussion_r656894762

docs: update contributing.md

---

templates/repository/common/.github/ISSUE_TEMPLATE/config.yml

alter text to avoid using double 'and'

fix: improve text in config

---

templates/repository/common/CONTRIBUTING.md

all credit to @masoudtahmasebi93  & closes https://github.com/ory/kratos/pull/1694

fix: missing link

---

templates/repository/common/ADOPTERS.md

fixes the .svg links in the README.
merged with the testing links still 🙈 
my bad, have to triple check PRs on Friday evening...

fix: .svg links

---

templates/repository/server/.github/pull_request_template.md

fixes PR template to use the new docs repository.

fix: update documentation link

---

templates/repository/common/CODE_OF_CONDUCT.md
templates/repository/common/CONTRIBUTING.md

- docs: update CONTRIBUTING.md + COC
Update CONTRIBUTING to add a section about adding new examples
update CONTRIBUTING to reflect the new Ory docs structure
update CONTRIBUTING with some language fixes and removing redundant info
update COC template from version 1.4. to 2.1

docs: update CONTRIBUTING & COC

---

templates/repository/common/ADOPTERS.md

Links in ADOPTERS.md still point to the fork. This fixes that. :)

fix: links in ADOPTERS

---

package-lock.json
package.json

Sorts package.json following a [standardized order](https://github.com/keithamus/sort-package-json).
- limits merge conflicts when two PRs add a new key
- allows finding entries in package.json faster
- less bikeshed debates about ordering of random data
introduces a new feature.
[contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
vulnerability. If this pull request addresses a security. vulnerability, I
confirm that I got green light (please contact
[security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
the changes.
works.

Sort package.json

---

scripts/sync.sh

The sync script prints a ton of output on CI. This adds structure that helps debug problems.

chore: improve debuggability of sync script

---

README.md

Add documentation on how to test a single repo

docs: testing a single repo

---

.github/workflows/test.yml

"Test / format" is inaccurate.

chore: improve CI task name

---

scripts/sync.sh

Git uses only the first commit message.

fix: merge both commit messages

---

.github/workflows/format.yml
Makefile
package-lock.json
package.json
templates/repository/common/CONTRIBUTING.md

Addresses parts of https://github.com/ory-corp/general/issues/735.

chore: format using Make

---

templates/repository/common/CONTRIBUTING.md

As discussed here https://github.com/ory/meta/pull/190#discussion_r978026199

chore: ignore top-level heading in toc in CONTRIBUTING.md

---

package-lock.json
package.json
templates/repository/common/.github/ISSUE_TEMPLATE/BUG-REPORT.yml
templates/repository/common/.github/ISSUE_TEMPLATE/DESIGN-DOC.yml
templates/repository/common/.github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
templates/repository/common/.github/ISSUE_TEMPLATE/config.yml
templates/repository/common/ADOPTERS.md

- remove open collective and defunct patreon
- rewrite the adopters intro to reflect the growth
of course we also need to fix the sync action for this to have any effect 😬

fix: revamp adopters.md

---

templates/repository/common/CONTRIBUTING.md

Broken links make it more difficult to contribute.
If this pull request addresses a security vulnerability, 
I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.

docs: update broken links in CONTRIBUTING.md

---

scripts/sync.sh
templates/repository/common/CONTRIBUTING.md

updating CONTRIBUTING to reflect recent changes from https://github.com/ory/awesome-ory

chore: update CONTRIBUTING.md
